### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by c3nIvailo** [bridgecrewio/AirIAM#36]
Hello, it looks like there is an issue with the latest version:

airiam --help
Traceback (most recent call last):
  File "/Users/ivo/Library/Python/3.8/bin/airiam", line 2, in <module>
    from airiam.main import run
  File "/Users/ivo/Library/Python/3.8/lib/python/site-packages/airiam/main.py", line 6, in <module>
    from airiam.find_unused.find_unused import find_unused
  File "/Users/ivo/Library/Python/3.8/lib/python/site-packages/airiam/find_unused/find_unused.py", line 4, in <module>
    from airiam.find_unused.PolicyAnalyzer import PolicyAnalyzer
  File "/Users/ivo/Library/Python/3.8/lib/python/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <module>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
  File "/Users/ivo/Library/Python/3.8/lib/python/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <dictcomp>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
TypeError: string indices must be integers

**Comment by dmarszal** [comment]
Confirmed, reproduced it Mint 18, CentOs 7.7 and Alpine docker image (alpine:3.11.3)

Steps to reproduce in Alpine:
# apk add py3-pip
# pip3 install airiam --user
# /root/.local/bin/airiam
Traceback (most recent call last):
  File "/root/.local/bin/airiam", line 2, in <module>
    from airiam.main import run
  File "/root/.local/lib/python3.8/site-packages/airiam/main.py", line 6, in <module>
    from airiam.find_unused.find_unused import find_unused
  File "/root/.local/lib/python3.8/site-packages/airiam/find_unused/find_unused.py", line 4, in <module>
    from airiam.find_unused.PolicyAnalyzer import PolicyAnalyzer
  File "/root/.local/lib/python3.8/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <module>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
  File "/root/.local/lib/python3.8/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <dictcomp>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
TypeError: string indices must be integers

**Comment by schosterbarak** [comment]
@metahertz are you getting the same?

**Comment by metahertz** [comment]
@schosterbarak Wasn't using latest version but I am seeing this indeed, investigating.

```
➜  ~ airiam --help
Traceback (most recent call last):
  File "/usr/local/bin/airiam", line 2, in <module>
    from airiam.main import run
  File "/usr/local/lib/python3.8/site-packages/airiam/main.py", line 6, in <module>
    from airiam.find_unused.find_unused import find_unused
  File "/usr/local/lib/python3.8/site-packages/airiam/find_unused/find_unused.py", line 4, in <module>
    from airiam.find_unused.PolicyAnalyzer import PolicyAnalyzer
  File "/usr/local/lib/python3.8/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <module>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
  File "/usr/local/lib/python3.8/site-packages/airiam/find_unused/PolicyAnalyzer.py", line 8, in <dictcomp>
    action_map = {a['prefix']: a for a in requests.get(ACTION_TABLE_URL).json()}
TypeError: string indices must be integers
```

**Comment by metahertz** [comment]
A JSON definitions file AirIAM depends on from has changed it's format upstream, causing this error. Will push a temporary PR to fix.

```
diff --git a/policy_sentry/shared/data/iam-definition.json b/policy_sentry/shared/data/iam-definition.json
index ac31383..c45d9a9 100644
--- a/policy_sentry/shared/data/iam-definition.json
+++ b/policy_sentry/shared/data/iam-definition.json
@@ -1,5 +1,5 @@
-[
-    {
+{
+    "a4b": {
         "service_name": "Alexa for Business",
         "prefix": "a4b",
         "privileges": [
@@ -10,6 +10,7 @@
                 "resource_types": [
                     {
                         "resource_type": "",
+                        "required": false,
                         "condition_keys": [],
                         "dependent_actions": []
                     }
```

@schosterbarak Will need to consume the new format in order to take endpoint updates.

**Comment by metahertz** [comment]
`python3 -m pip install airiam==0.1.39` is working based on the merged PR and not producing the error.
