### ISSUE TITLE
Error with recommend_groups

### ISSUE THREAD

**Issue by abernalneo** [bridgecrewio/AirIAM#56]
Does anyone know what is wrong in this output? After I execute airiam recommend_groups I get this:

_AirIAM - Least privilege AWS IAM Terraformer_

_To continuously scan configurations, try the Bridgecrew free community plan._
_https://www.bridgecrew.io_

INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
Reusing local data
INFO:root:Analyzing data for account **XXXXXXXXXXXXX** (masked)
INFO:root:Using the default UserOrganizer
Traceback (most recent call last):
  File "/usr/local/bin/airiam", line 5, in <module>
    run()
  File "/usr/local/lib/python3.7/dist-packages/airiam/main.py", line 36, in run
    report_with_recommendations = recommend_groups(logger, runtime_results, args.last_used_threshold)
  File "/usr/local/lib/python3.7/dist-packages/airiam/recommend_groups/recommend_groups.py", line 19, in recommend_groups
    runtime_iam_report.set_reorg(organizer.get_user_clusters(runtime_iam_report))
  File "/usr/local/lib/python3.7/dist-packages/airiam/recommend_groups/recommend_groups.py", line 38, in get_user_clusters
    simple_user_clusters = self._create_simple_user_clusters(human_users, iam_data['AccountGroups'], iam_data['AccountPolicies'])
  File "/usr/local/lib/python3.7/dist-packages/airiam/recommend_groups/recommend_groups.py", line 84, in _create_simple_user_clusters
    if PolicyAnalyzer.policy_is_write_access(policy_document):
  File "/usr/local/lib/python3.7/dist-packages/airiam/find_unused/PolicyAnalyzer.py", line 56, in policy_is_write_access
    action_map[action_service]['privileges']))
KeyError: 'ecr-public'

**Comment by abernalneo** [comment]
Hello.
I found out that this error appeared for a lot of new AWS Services that weren't included in iam_definition.json file (https://github.com/salesforce/policy_sentry). That database was updated 16 days ago.
